version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        update-types:
          - minor
          - patch
