version: 2

multi-ecosystem-groups:
  minor-and-patch:
    schedule:
      interval: 'quarterly'
    commit-message:
        prefix: 'fix'
        prefix-development: 'build'
        include: 'scope'

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'minor-and-patch'
    groups:
      production:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
      development:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-groups: 'minor-and-patch'
    update-types:
      - minor
      - patch
