name: "Create GitHub App Token"
description: "GitHub Action for creating a GitHub App installation access token"
author: "Gregor Martynus and Parker Brown"
branding:
  icon: "lock"
  color: "gray-dark"
inputs:
  app_id:
    description: "GitHub App ID"
    required: true
  private_key:
    description: "GitHub App private key"
    required: true
  owner:
    description: "GitHub App owner (defaults to current repository owner)"
    required: false
  repositories:
    description: "Repositories to install the GitHub App on (defaults to current repository if owner is unset)"
    required: false
  revoke:
    description: "Whether to revoke the token when the current job is complete"
    required: false
    default: "true"
outputs:
  token:
    description: "GitHub installation access token"
runs:
  using: "node20"
  main: "dist/main.cjs"
  post: "dist/post.cjs"
