name: Check Action Typing

on:
  - pull_request

permissions:
  contents: read

jobs:
  check_action_typing:
    name: Check Action Typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Action Typing
        uses: typesafegithub/github-actions-typing@0dc5690c35c564d354dc0c23c56559f0813ed3ac
